### ISSUE TITLE
KeyError in ircutil.py line 94

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/Wendy#19]
```
2015-01-10 16:34:01 [-] Sending mode requests +b [u'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!*@*$##FIX_YOUR_CONNECTION']
2015-01-10 16:34:01 [-] Setting -b on aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!*@*$##FIX_YOUR_CONNECTION in #steamdb in 7200 seconds
2015-01-10 16:34:01 [-] buffers emptied for #steamdb
2015-01-10 16:34:01 [IRCBot (TLSMemoryBIOProtocol),client] Traceback (most recent call last):
          File "/home/xpaw/abbott/abbott/transport.py", line 97, in send_event
            callback_obj.received_event(event)
          File "/home/xpaw/abbott/abbott/pluginbase.py", line 281, in received_event
            method(event)
          File "/home/xpaw/abbott/abbott/plugins/ircutil.py", line 94, in on_event_irc_on_unknown
            for callback in self.pendingwhoises.pop(nick):
        KeyError: u'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
```

**Comment by xPaw** [comment]
This also happens when trying to kick by a hostmask:

```
2015-01-12 17:31:30 [IRCBot (TLSMemoryBIOProtocol),client] Traceback (most recent call last):
          File "/home/xpaw/abbott/abbott/transport.py", line 97, in send_event
            callback_obj.received_event(event)
          File "/home/xpaw/abbott/abbott/pluginbase.py", line 281, in received_event
            method(event)
          File "/home/xpaw/abbott/abbott/plugins/ircutil.py", line 94, in on_event_irc_on_unknown
            for callback in self.pendingwhoises.pop(nick):
        KeyError: u'xpaw!xpaw@unaffiliated/xpaw'

2015-01-12 17:31:58 [IRCBot (TLSMemoryBIOProtocol),client] User xPaw!xPaw@unaffiliated/xpaw is auth'd to perform kick
```

**Comment by RJacksonm1** [comment]
Can't repro. Already been fixed?
